coverage:
  acceptable: 50%
codeToTestRatio:
  code:
    - '**/*.rb'
    - '!test/*.rb'
  test:
    - '**/*.rb'
testExecutionTime:
  acceptable: 1min
diff:
  path: .octocov/report.json
push:
  enable: true
  if: env.GITHUB_REF == 'refs/heads/main'
comment:
  enable: true
report:
  if: env.GITHUB_REF == 'refs/heads/main'
  path: .octocov/report.json
