coverage:
  acceptable: 50%
  badge:
    path: docs/coverage.svg
codeToTestRatio:
  code:
    - '**/*.rb'
    - '!test/*.rb'
  test:
    - '**/*.rb'
  badge:
    path: docs/ratio.svg
testExecutionTime:
  acceptable: 1min
  badge:
    path: docs/time.svg
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
push:
  if: is_default_branch
comment:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
