name: Example (Print the available attributes of context)

on:
  push:

jobs:
  pp-context:
    runs-on: ubuntu-latest
    steps:
      - uses: k1LoW/github-script-ruby@v1
        with:
          script: |
            pp context
