name: Integration

on:
  push:

jobs:
  test-return:
    name: 'The return value of `script` can be retrieved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: output-set
        uses: ./
        with:
          script: core.get_input('input')
          result-encoding: string
          input: hello world
      - run: |
          if [[ "${{ steps.output-set.outputs.result }}" != "hello world" ]]; then
            exit 1
          fi
  test-context:
    name: 'Can get values from `context`'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: context-payload
        uses: ./
        with:
          script: |
            exit 1 unless context.payload.repository.default_branch == 'main'
      - id: context-job
        uses: ./
        with:
          script: |
            exit 1 unless context.job == 'test-context'
  test-gems:
    name: 'Not affected by gems in other steps'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: |
          rm -f Gemfile Gemfile.lock
          bundle init
          echo "gem 'rubocop', '1.22.1'" >> Gemfile
          bundle install
      - uses: ./
        with:
          script: |
            require 'rubygems'
            exit 1 if Gem::Specification.all_names.include? 'rubocop-1.22.1'
  test-gemfile:
    name: 'Can change Gemfile to use'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          script: |
            require 'rubygems'
            exit 1 unless Gem::Specification.all_names.include? 'rubocop-1.22.1'
            exit 1 if Gem::Specification.all_names.include? octokit-4.20.0'
          gemfile: |
            source 'https://rubygems.org'
            gem 'rubocop', '1.22.1'
