name: Test

on:
  push:

jobs:
  test-return:
    runs-on: ubuntu-latest
    container: ghcr.io/k1low/github-script-ruby-base:latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: bundle install
      - name: Run test
        run: bundle exec ruby test/run_test.rb
      - uses: k1LoW/octocov-action@v0
